NOTE:  Execute each of these statements one at a time in the HSQL Database Manager

create table contact(
id integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1) ,
first_name varchar(50),
last_name varchar(50),
date_of_birth date,
married boolean,
children int
);


insert into contact (first_name, last_name, date_of_birth, married, children) values ('Barack', 'Obama', '1961-08-04', true, 2);
insert into contact (first_name, last_name, date_of_birth, married, children) values ('George', 'Bush', '1946-07-06', true, 2);
insert into contact (first_name, last_name, date_of_birth, married, children) values ('Oprah', 'Winfrey', '1954-01-29', false, 0);
insert into contact (first_name, last_name, date_of_birth, married, children) values ('Tiger', 'Woods', '1975-12-30', false, 2);
insert into contact (first_name, last_name, date_of_birth, married, children) values ('Hank', 'Aaron', '1935-02-05', true, 6);
insert into contact (first_name, last_name, date_of_birth, married, children) values ('Hilary', 'Clinton', '1947-10-26', true, 1);
insert into contact (first_name, last_name, date_of_birth, married, children) values ('Anne', 'Hathaway', '1982-11-12', true, 0);
insert into contact (first_name, last_name, date_of_birth, married, children) values ('Ben', 'Affleck', '1972-08-15', true, 3);
insert into contact (first_name, last_name, date_of_birth, married, children) values ('Robin', 'Meade', '1969-04-21', true, 0);
insert into contact (first_name, last_name, date_of_birth, married, children) values ('Pope', 'Francis', '1936-12-17', false, 0);

create table developer_contact(
id integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1) ,
first_name varchar(50),
last_name varchar(50),
date_of_birth date,
married boolean,
children int
);

insert into developer_contact (first_name, last_name, date_of_birth, married, children) values ('James', 'Gosling', '1955-05-19', true, 2);
insert into developer_contact (first_name, last_name, date_of_birth, married, children) values ('Donald', 'Knuth', '1938-01-10', true, 2);
